### ISSUE TITLE
Support for FireCode font with programming ligatures

### ISSUE THREAD

**Issue by hastebrot** [termux/termux-styling#1]
>Fira Code is a Fira Mono font extended with a set of ligatures for common programming multi-character combinations. This is just a font rendering feature: underlying code remains ASCII-compatible. This helps to read and understand code faster.

https://github.com/tonsky/FiraCode

There are other terminals that work (Konsole) and some that don't work (iTerm 2, rxvt):

https://github.com/tonsky/FiraCode#terminals-support

**Comment by hastebrot** [comment]
Wow, this works just out-of-the-box?

**Comment by fornwall** [comment]
Nice, haven't seen this kind of font with ligatures before! I've submitted version 0.8 of Termux:Styling to Google Play, should be available in a couple of hours max.

Yes, it works out of the box after light testing, let me know if you find any glitch with the Terminal behaviour!

The Termux terminal text rendering causes e.g. `<-` to be rendered as a composed ligature if all text attributes are same for `<` and `-`, which is the common case. If a text attribute (color, background, bold, italic, ...) differs between the  `<` and `-`, such as when placing the cursor one of them, they are rendered as separate characters, which I think is a sensible behaviour.

**Comment by hastebrot** [comment]
Version 0.8 is available. FiraCode works great in Termux so far. The rendering as separate characters while editing makes sense.

Thank you very much!

**Comment by hastebrot** [comment]
Added Termux to FiraCode's `README.md`: https://github.com/tonsky/FiraCode/pull/97

**Comment by hastebrot** [comment]
Since version 1.000 it switched to `calt` which causes the separate characters. So it is ok.

>Switched to calt instead of liga. You can now “step inside” the ligature in text editors.

**Comment by davemackintosh** [comment]
This doesn't seem to work anymore, no ligatures on my android 8.0 and latest Termux/Styling in neovim.
