### ISSUE TITLE
Does not appear in the google play for work store

### ISSUE THREAD

**Issue by ure** [termux/termux-styling#10]
https://play.google.com/work/search?q=termux&c=apps
(Only Termux and Termux:Api are available)

**Comment by fornwall** [comment]
Unfortunately I cannot enable the app for Google Play for Work, as I get the following message (living in Sweden):

    Distributing paid apps in Google Play for Work is not currently supported in your country.

Hopefully this will be changed in the future in Google Play.

What you can do for now is to set the style and font manually:

1. Put fonts (like those in the [fonts/ folder here](https://github.com/termux/termux-styling/tree/master/app/src/main/assets/fonts)) in `$HOME/.termux/font.ttf` (which despite the filename may be an OTF file).

2. Put color themes (like those in the [colors/ folder here](https://github.com/termux/termux-styling/tree/master/app/src/main/assets/colors)) in `$HOME/.termux/colors.properties`.

3. Execute `termux-reload-settings` (or restart the app).
