### ISSUE TITLE
More fonts?

### ISSUE THREAD

**Issue by Kutsan** [termux/termux-styling#11]
Is it possible to add more fonts like Roboto Mono, Meslo and [etc](https://github.com/powerline/fonts).? Current ones a bit bad for me.

**Comment by fornwall** [comment]
Sure!

About Roboto Mono: Is not that already the default monospace font on Android (so Termux should already be using that one by default)?

About Meslo: I can look at adding this.

**Comment by Kutsan** [comment]
Thank you so much. And that one not Powerline compatible. Can't see special characters.

**Comment by tdilo** [comment]
Please also consider adding the Go Mono fonts: https://blog.golang.org/go-fonts

**Comment by fornwall** [comment]
The Go, Meslo and Roboto fonts have now been added in version 0.14 of the app, which is rolling out as an update.

Feel free to create additional issues for more desired fonts!

**Comment by Kutsan** [comment]
Thank you so much!

**Comment by HendrikPetertje** [comment]
so sorry to re-open this discussion. can powerline-fonts be added? 
https://github.com/powerline/fonts
they are basically the same as the normals but include extra characters

**Comment by kutsan** [comment]
@HendrikPetertje Current fonts already have powerline characters. You can find Roboto Mono for Powerline in the app.

**Comment by amitsharma123234** [comment]
How to set the font back to default

**Comment by xeffyr** [comment]
> How to set the font back to default

Select default maybe ?
