### ISSUE TITLE
Color Request: Nord theme

### ISSUE THREAD

**Issue by d3rrial** [termux/termux-styling#13]
Hey there, I really like both termux and the styling addon for it!

~~I personally really like the Nord theme () and I use it on all my devcices, but unfortunately termux doesn't allow for custom colors. Termux has a color scheme, Ocean Dark, which is very similar to Nord, but is nonetheless distinctly different as well.~~

~~I would appreciate it, if something like this could be looked into. :)~~

Edit: I really like the [Nord scheme](https://github.com/arcticicestudio/nord) and I unofficially ported it to termux. Is it possible to contact the creator(s) and include it among the standard ones?

```
foreground= #d8dee9
background= #2e3440
cursor= #d8dee9

color0= #3b4252
color1= #bf616a
color2= #a3be8c
color3= #ebcb8b
color4= #81a1c1
color5= #b48ead
color6= #88c0d0
color7= #e5e8f0

color8= #4c566a
color9= #bf616a
color10= #a3be8c
color11= #ebcb8b
color12= #81a1c1
color13= #b48ead
color14= #8fbcbb
color15= #eceff4
```

**Comment by fornwall** [comment]
Thanks - this will be available in a version `0.17` update in a couple of hours.
