### ISSUE TITLE
Cmatrix PKG 


### ISSUE THREAD

**Issue by MrSaiZaw** [termux/termux-styling#144]
**Feature description**

**Reference implementation**

**Comment by MrSaiZaw** [comment]
I want to use matrix style in termux..

**Comment by Grimler91** [comment]
So install and use the cmatrix package

**Comment by MrSaiZaw** [comment]
Hello Termux/Termux-StylingTeam,

Can I stop this .....matrix
And another Can use?

Thank you and best regards

specialties ᰜ™

**Comment by MrSaiZaw** [comment]
Yes, you can do that.

specialties ᰜ™
