### ISSUE TITLE
The debug build is expired. 

### ISSUE THREAD

**Issue by gitdrug** [termux/termux-styling#147]
The debug build https://github.com/termux/termux-styling/actions/workflows/debug_build.yml is expired how would i force it to rebuild the debug build?

**Comment by gitdrug** [comment]
Who ever owns this repo add like a space to the readme to make it rebuild the debug build

**Comment by DessertArbiter** [comment]
anyone looking for the debug build can use this fork for now
https://github.com/rose-pine/termux

**Comment by Grimler91** [comment]
Available from CI build of latest commit for now: https://github.com/termux/termux-styling/actions/runs/2066979295
