### ISSUE TITLE
Color scheme: New GNOME Terminal

### ISSUE THREAD

**Issue by slashdevslashurandom** [termux/termux-styling#164]
**Feature description**
The newer versions of GNOME have implemented a new color scheme, different from the Tango-derived one used before. I personally think it looks rather nice and should be included in Termux.

```
color0 (black): #171421
color1 (red): #c01c28
color2 (green): #26a269
color3 (yellow): #a2734c
color4 (blue): #12488b
color5 (magenta): #a347ba
color6 (cyan): #2aa1b3
color7 (gray): #d0cfcc
color8 (dark gray): #5e5c64
color9 (bright red): #f66151
color10 (bright green): #33d17a
color11 (bright yellow): #e9ad0c
color12 (bright blue): #2a7bde
color13 (bright magenta): #c061cb
color14 (bright cyan): #33c7de
color15 (white): #ffffff
```

**Reference implementation**
This is a screenshot of GNOME 41's terminal app's color scheme settings, displaying all 16 colors.

![Screenshot from 2022-05-16 18-38-19](https://user-images.githubusercontent.com/53902042/168631016-32457413-9e27-4456-b2de-a4b97c178d89.png)

**Comment by alive4ever** [comment]
The suggested colorscheme feels pretty nice.

![Preview of the suggested colorscheme](https://user-images.githubusercontent.com/7654911/185864022-ea323dd1-70f9-45a2-b391-99291248f741.png)
