### ISSUE TITLE
Install But Don't Show & I Can't Use It. 

### ISSUE THREAD

**Issue by SKVAI** [termux/termux-styling#167]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version:
* Android OS version:
* Device model:

**Comment by thunder-coding** [comment]
What do you mean by "I can't use it", please elaborate. We are not astrologists (or similar) that we can predict what you said. 

Closing the ticket, in case you have any **real** problem, consider commenting
