### ISSUE TITLE
Can't install Termux:Styling in armv8l phone

### ISSUE THREAD

**Issue by UrNightmaree** [termux/termux-styling#171]
**Problem description**

Cannot install Termux:Styling in armv8l phone whether install using F-Droid nor GitHub releases.

**Steps to reproduce**

No any steps to reproduce this issue.

**Expected behavior**

When I tried to install Termux:Styling from GitHub releases, the installation returns error. So I switched to F-Droid and try to install Termux:Styling, still returns error when installing Termux:Styling.

**Additional information**

* Termux application version: 0.118.0
* Android OS version: Android 11
* Device model: Galaxy A10

**Comment by ChiefMikeK** [comment]
Where did you get your Termux.apk from, f-droid or github?  
The Signing keys must "ALL" match, delete the failed downloads then re-download from the same place where you got Termux 0.118.0  
It's also possible that the download was corrupted.

**Comment by pseudoparenchymatous** [comment]
I also can't install the app. I downloaded Termux from GitHub, but it says the styling app must come from the same source as Termux despite the styling app not having any GitHub releases. Is GitHub and F-droid considered the same source?

**Comment by UrNightmaree** [comment]
Maybe not.

**Comment by pseudoparenchymatous** [comment]
> F-Droid and GitHub are not same. They are built on different machines and are signed by different keys. Besides that, GitHub builds are debuggable.
> 
> You can grab the latest Styling here: https://github.com/termux/termux-styling/suites/8393125482/artifacts/370781574 (artifact expires in ~78 days).

Thank you. I was too hasty after commenting. I uninstalled the GitHub version to install the F-droid version of Termux. The styling app from F-droid is now installable. 

After learning that the styling app can be downloaded from the **Actions** tab, I uninstalled both to install the GitHub version of both and was successful.

I used `termux-backup` before uninstalling but it didn't save my zsh configuration. Glad I just started using Termux and didn't configure much yet.

**Comment by agnostic-apollo** [comment]
@UrNightmaree Where did you install termux from? If installed from playstore, then can't install F-Droid or Github releases.

**Comment by UrNightmaree** [comment]
I downloaded Termux from GitHub

**Comment by agnostic-apollo** [comment]
Download termux-styling apk from https://github.com/termux/termux-styling/actions/runs/3096026860 and run `adb install -r termux-styling.apk` from pc and post the error.

**Comment by UrNightmaree** [comment]
Sorry for the long responding, I've figured out to install Termux:Styling from GitHub. And also my phone is not fully 64-bit mode, it still stuck on 32-bit mode.
