### ISSUE TITLE
cant find github version of termux styling. its link is expired please provide new one. 
Termux version - 118
Android os - 10 Miui12
Device Poco F1

### ISSUE THREAD

**Issue by devalllex** [termux/termux-styling#172]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version:
* Android OS version:
* Device model:

**Comment by agnostic-apollo** [comment]
@Grimler91 if next version is releasable, can add something like https://github.com/termux/termux-float/commit/529268a1

**Comment by agnostic-apollo** [comment]
You can grab a build from https://github.com/termux/termux-styling/actions/runs/2929688613 for now.
