### ISSUE TITLE
How to contribute? 

### ISSUE THREAD

**Issue by pseudoparenchymatous** [termux/termux-styling#180]
I want to contribute new fonts and themes. But I'm new to contributing, so I don't know how. I have this steps in mind:
1. Fork the repo
2. Clone the fork to local
3. Add new `.ttf` and `.properties` files

Now I'm stuck, how can I build an apk from my changes so I can install it in my phone to test? Done with `pkg install kotlin`.

After that I assume next is:
1.  Push to fork
2.  Pull request

**Comment by MrAdityaAlok** [comment]
> Now I'm stuck, how can I build an apk from my changes so I can install it in my phone to test?

- Enable github actions in your fork.
- Push your changes to your fork. Github will build debug apk for you.

> After that I assume next is:

> Push to fork
> Pull request

Yes.
