### ISSUE TITLE
Color Scheme Suggestion: Smyck

### ISSUE THREAD

**Issue by shivaprsdv** [termux/termux-styling#19]
Hello,
I regularly use the [Smyck](http://color.smyck.org) color scheme on my Mac, so I ported it for
using with Termux. Thought I'd share, please consider adding it:
```
#https://github.com/hukl/Smyck-Color-Scheme/blob/master/colors
background=#212121
foreground=#f7f7f7
cursor=#218693

color0=#000000
color1=#c75646
color2=#8eb33b
color3=#d0b03c
color4=#4e90a7
color5=#c8a0d1
color6=#218693
color7=#b0b0b0
color9=#e09690
color8=#5d5d5d
color10=#cdee69
color11=#ffe377
color12=#9cd9f0
color13=#fbb1f9
color14=#77dfd8
color15=#f7f7f7
```
Thanks for making Termux, it's awesome. Keep up the good work. 🙂

**Comment by fornwall** [comment]
Thanks a lot! This will be part of the next update (version 0.18) available shortly!
