### ISSUE TITLE
Please provide release APKs here

### ISSUE THREAD

**Issue by davidfetter** [termux/termux-styling#190]
**Feature description**

Termux itself is available as a universal APK, among other versions, from Github for people who can't or won't use either F-Droid or the Google Play Store. This is a handy feature. Please make released builds available here in a similar way.

**Comment by Grimler91** [comment]
You have debug builds among the CI artifacts when logged in to github, latest at the moment is: https://github.com/termux/termux-styling/actions/runs/3603709220. We should tag a new release quite soon also though

**Comment by agnostic-apollo** [comment]
It does show in Chrome on Android, you are likely not logged in. Try enabling desktop site from options, although shouldn't be needed.

**Comment by davidfetter** [comment]
The assets I see in releases are source code, not APKs. The ones from CI are debug builds.

Would you please put up release APKs?

Thanks!
