### ISSUE TITLE
Solarized Light style incorrectly reverses light/dark colors

### ISSUE THREAD

**Issue by necopinus** [termux/termux-styling#2]
The Solarized Light style (`solarized-light.properties`) incorrectly reverses light/dark accent colors. In particular, `color0` - `color15` should be _identical_ between the light and dark variants of the color scheme, with the only changes being to the foreground and background colors.

An easy way to see this is to use the official ViM Solarized color scheme (or any of the other variants out there); colors are currently only displayed correctly for Termux's Solarized Light style when ViM's `background` is set to `dark` (opposite of what it should be).

The attached zip file contains a version of the Solarized Light style that should fix this issue, as well as a patch between the old and new file (if so desired).

[solarized-light.zip](https://github.com/termux/termux-styling/files/123690/solarized-light.zip)

**Comment by fornwall** [comment]
Thanks! The fix will be in an updated 0.9 release available in the Play Store or F-Droid within a day!
