### ISSUE TITLE
Use nerd fonts

### ISSUE THREAD

**Issue by luisdavim** [termux/termux-styling#20]
Hi, would it be possible to use nerd fonts instead of just powerline patched fonts?
https://github.com/ryanoasis/nerd-fonts I use some font awesome glyphs on my tmux status bar that currently are not displayed in termux, this should fix that.

**Comment by fornwall** [comment]
Thanks, looks interesting!

Do you know the difference between variations, like with these:

```
Ubuntu Mono Nerd Font Complete Mono Windows Compatible.ttf
Ubuntu Mono Nerd Font Complete Mono.ttf
Ubuntu Mono Nerd Font Complete Windows Compatible.ttf
Ubuntu Mono Nerd Font Complete.ttf
Ubuntu Mono derivative Powerline Nerd Font Complete Mono Windows Compatible.ttf
Ubuntu Mono derivative Powerline Nerd Font Complete Mono.ttf
Ubuntu Mono derivative Powerline Nerd Font Complete Windows Compatible.ttf
Ubuntu Mono derivative Powerline Nerd Font Complete.ttf
```

Of the above, is `Ubuntu Mono derivative Powerline Nerd Font Complete Mono.ttf` the suitable choice here?

**Comment by luisdavim** [comment]
I've tried some variations like that and couldn't really tell the difference, but I think that, for example between:
```
Ubuntu Mono Nerd Font Complete.ttf
```
And
```
Ubuntu Mono Nerd Font Complete Mono.ttf
```

Is that the symbols are also monospace. 

I use `Ubuntu Mono Nerd Font Complete.ttf` and it works for me.

**Comment by fornwall** [comment]
So `Ubuntu Mono Nerd Font Complete.ttf` does also have powerline fonts?

**Comment by luisdavim** [comment]
Yes, seems to

**Comment by luisdavim** [comment]
some info here: https://github.com/ryanoasis/nerd-fonts/issues/165#issuecomment-317393251 and here: https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting#tldr

**Comment by luisdavim** [comment]
hi, any updates on this?
maybe you can use this:
```
getNerdFont() {
  project='ryanoasis/nerd-fonts/'
  tag=$(curl -s https://api.github.com/repos/${project}/releases/latest | jq -r '.tag_name' | tr -d 'v' )
  url="https://raw.githubusercontent.com/${project}/${tag}/patched-fonts/${1// /%20}"
  curl -fLo "${1}" "${url}"
}
```

**Comment by fornwall** [comment]
Thanks for the snippet!

I've updated the fonts with nerd fonts where available, let me know if there are any problems or if you would like any nerd font added!

**Comment by luisdavim** [comment]
Awesome. Thanks.
