### ISSUE TITLE
Can't install the app

### ISSUE THREAD

**Issue by Aridlvory** [termux/termux-styling#205]
**Problem description**

I cannot install the termux styling plugins on my device.. the app fails to install
I was using fdroid version of termux and the app worked perfectly.
But when I started using the github version (same version)
The app fails to install

I tried this in my 2 device... 

First device says "app cannot install"
Device info
Device name: SM-J600GF
Android 10
Termux version 0.118.0

Second device says "app cannot install because it conflicts with another package"
Device info
Device name: SM-T220
Android 13
Termux version 0.118.0
**Steps to reproduce**

Install the latest version
**Expected behavior**

Device says cannot install the app because it conflicts with another package
**Additional information**

* Termux application version: 0.118.0
* Android OS version: 10 & 13
* Device model: SM-J600GF & SM-T220

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#Installation
