### ISSUE TITLE
all your GitHub debug builds have expired again

### ISSUE THREAD

**Issue by cpw** [termux/termux-styling#207]
**Problem description**

Unable to obtain a GitHub signed build of styling due to all builds being expired in GitHub actions, and only one fdroid signed build is available in releases.
**Steps to reproduce**

Try and download any build other than v.30 fdroid. They don't exist and have all expired. The fdroid build is not compatible with GitHub builds of the primary termux application.
**Expected behavior**

I would hope to have a build I can use.
**Additional information**

* Termux application version:
* Android OS version: 118 latest GitHub build
* Device model: oneplus9pro

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-styling/actions/runs/5414834887
