### ISSUE TITLE
Cannot install app from f-droid

### ISSUE THREAD

**Issue by Nolancc** [termux/termux-styling#228]
**Problem description**

I cannot install the app onto my device using f-droid.
When I try to install it using f-droid it says app not installed due to conflicts with existing package.
**Steps to reproduce**

Open droidlfy and set installation type to legacy.
Than search for the app and try to install it
**Expected behavior**

I just want to install the app
**Additional information**

* Termux application version:0.118.9
* Android OS version:14
* Device model:pixel 6a

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-app#Installation

**Comment by Nolancc** [comment]
I have installed both Termux and Termux:styling from f-droid and i still have this issue
