### ISSUE TITLE
Purchase not possible on Pixelbook

### ISSUE THREAD

**Issue by carlthewebmaster** [termux/termux-styling#29]
Apologies in advance if this is the wrong place to report.  On my pixelbook, when I try to purchase Termux:styling, the price is striked out (line through text) and there's a message "This app may not be optimized for your device". Can't install.  Is there a way to purchase and use this on a chromebook (with android support)?

**Comment by carlthewebmaster** [comment]
Unrelated to this repo entirely. Side note for future searchers: pinch to zoom text size!

Sorry for any confusion on my part.

**Comment by sdrausty** [comment]
https://wiki.termux.com/wiki/User_Interface
