### ISSUE TITLE
"Cannot install due to unknown error"

### ISSUE THREAD

**Issue by baconicsynergy** [termux/termux-styling#3]
Attempting to install termux-styling 0.10 yields the above error message. Verizon Galaxy S6, Android version 5.1.1

**Comment by fornwall** [comment]
All Termux add-ons needs to be signed with the same key, which means that you cannot e.g. install Termux from F-Droid and termux-styling from Google Play (or vice versa), since F-Droid uses a custom key for signing. Could this explain the problem?

**Comment by fornwall** [comment]
Closing this in favour of https://github.com/termux/termux-app/issues/57.
