### ISSUE TITLE
update nerd fonts: Github, Python symbols missing

### ISSUE THREAD

**Issue by ewilderj** [termux/termux-styling#33]
Is it possible to refresh the nerd fonts you use in styling?

Currently missing are the glyphs for source control and Python (0xe907 and 0xe928) that I noticed. 

Thank you for such an excellent application! Delighted to pay for it.

**Comment by aquatix** [comment]
2.0.0 has quite some improvements :) And indeed, I gladly paid for it (termux is neat and good fonts and colours only make it better).

**Comment by fornwall** [comment]
Thanks! Version 0.24 of the Termux:Styling app, which has been released and should be available as an update shortly, has now been updated to use Nerd Fonts 2.0 (from the previous 1.2 version). Let me know if there is any problem!

Note that you have to select the font again in the font list to receive the updated font.
