### ISSUE TITLE
Customizable 

### ISSUE THREAD

**Issue by lukeeey** [termux/termux-styling#34]
It would be nice to have be able to set our own colours. This cant be too hard to implement.

**Comment by feklee** [comment]
Yes, especially as the current themes with white background lack contrast. I would like to have a theme like *Base16 Google Light*, but with foreground #000 instead of the dark gray. If I want to reduce contrast, then I can dim my screen. More often than not, however, contrast is too low.

**Comment by feklee** [comment]
On #termux IRC I was directed towards:

    $ termux-reload-settings -h
    usage: termux-reload-settings
    Use without arguments to reload settings after modifying any of:
      ~/.termux/colors.properties
      ~/.termux/font.ttf
      ~/.termux/termux.properties

Own colors can be configured in  `colors.properties`. This solves the issue for me. (A high contrast black on white theme with colors would still be appreciated, though.)
