### ISSUE TITLE
Allow to load additional font files from internal storage/sdcard

### ISSUE THREAD

**Issue by hsiktas** [termux/termux-styling#35]
Some of us prefer to use proprietary fonts like like [Operator Mono](https://www.typography.com/fonts/operator/overview/) or [PragmataPro](https://www.fsd.it/shop/fonts/pragmatapro/) which obviously can't be included in termux-styling.
Can we please have a way to easily add these fonts afterwards?

**Comment by Neo-Oli** [comment]
This can be done by copying a ttf file to ~/.termux/font.ttf and running `termux-reload-settings`.
