### ISSUE TITLE
Not Available in my country!

### ISSUE THREAD

**Issue by xarrijorge** [termux/termux-styling#37]
Awesome app, save me buying a new computer as I can now use my chromebooks for dev work. the only problem is I cant download the styling app in my country. Please make it available for download in West Africa

**Comment by xeffyr** [comment]
Did you tried to download Termux from F-Droid (via site or app) ?
Link: https://f-droid.org/en/packages/com.termux/

**Comment by fornwall** [comment]
Thanks for reporting! I've checked every country that is possible to check in the developer console. If it is still not available in your country I think you will have to contact support for the Play Store!
