### ISSUE TITLE
Nerd fonts 2.0.0 has been released in April

### ISSUE THREAD

**Issue by aquatix** [termux/termux-styling#39]
First of all: thanks for Termux and this styling addon, I use it every day to develop and work with my servers. It simply is great.

I noticed the update of termux-styling today in the Playstore, and also saw that Nerd fonts was updated in November of last year. Since then, a release with quite some improvements has been done.

It would be cool if this version of nerd-fonts could be included.

Anyway, thanks for Termux!

**Comment by fornwall** [comment]
Thanks! Version 0.24 of the Termux:Styling app, which has been released and should be available as an update shortly, has now been updated to use Nerd Fonts 2.0. Let me know if there is any problem!

Note that you have to select the font again in the font list to receive the updated font.
