### ISSUE TITLE
font selection is limited NEED BIG FONTS

### ISSUE THREAD

**Issue by pleabargain** [termux/termux-styling#41]
device: asus chromebook flip c302
OS: Version 71.0.3578.27 (Official Build) beta (64-bit)

You can see in this video 
https://youtu.be/-Py_SKXo8cs
that there appears to be **no appreciable difference in size between the default and the 16**

Is this something that is going to be addressed in the near future?

**Comment by Grimler91** [comment]
You can zoom by pinch-zooming to make it bigger/smaller, and that should work with any font
