### ISSUE TITLE
fail installing

### ISSUE THREAD

**Issue by n00b2h4ck3r** [termux/termux-styling#46]
Error package installing

**Comment by diehard88** [comment]
@n00b2h4ck3r 

Mee too.

**Comment by xeffyr** [comment]
Perhaps you are mixing installations from f-droid and google play ?

**Comment by diehard88** [comment]
@xeffyr 


Yes............

**Comment by xeffyr** [comment]
@diehard88 In that case it's not a bug. You can't mix termux apks from google play and f-droid because of different signature keys.

**Comment by xeffyr** [comment]
From https://wiki.termux.com/wiki/Termux:Styling:
> Important: Do not mix installations of Termux and Addons between Google Play and F-Droid.

**Comment by diehard88** [comment]
one last question:  do I need to install styling apk even I clone/build this repository?

Many thanks!

**Comment by xeffyr** [comment]
@diehard88 To install styling addon you need APK file. You can either download it or build from this repository.

**Comment by noorul** [comment]
Should termux also be installed from F-droid?

**Comment by xeffyr** [comment]
Yes, if you are installing Termux:Styling from F-Droid, everything else like Termux app and other add-ons should be installed from same source (F-Droid) too. That's all due to different signature key.

https://github.com/termux/termux-app#installation

**Comment by noorul** [comment]
Thanks @xeffyr, issue got fixed after moving termux source to F-Droid
