### ISSUE TITLE
Theme Request: Spacemacs (open source editor with 18K stars)

### ISSUE THREAD

**Issue by wordyallen** [termux/termux-styling#59]
Theme repo: https://github.com/nashamri/spacemacs-theme
Main repo: https://github.com/syl20bnr/spacemacs

Thanks for considering it :)

**Comment by wordyallen** [comment]
I found one more repo with the palette.  I can link to other  guides too. https://github.com/raphamorim/astrofish

**Comment by fornwall** [comment]
@wordyallen Thanks for the suggestion! Could you try to create a properties file?

To experiment, put the file at `$HOME/.termux/colors.properties`, and to apply it run `termux-reload-settings`. When you are satisfied that it works you can write it here and I'll include it in an app update!

**Comment by AbdullahM0hamed** [comment]
Based on: [https://raw.githubusercontent.com/nashamri/spacemacs-theme/screenshots/guide-generic.png
](url) 
I have figured out that the highlighted portions map to the following colours: 
  keyword = color6
  base = foreground
  bg = background
  func = color12
  comment/var = color3
  type/str = color12

I have no idea how to get the border in emacs, so border, act1, and act2 remain unchanged. 

Unfortunately comment and var share the same color property, and so do type and str, which means that I couldn't create a 100% accurate version of it.


Screenshot: 
![Screenshot_20191001-201529](https://user-images.githubusercontent.com/25087116/65996834-1a596300-e490-11e9-849a-e544a68888ff.png)


If that's satisfactory, here's the colors.properties: 

```
foreground=#adb0a2
background=#292b2e
cursor=#eead0e
color0=#1C2023
color1=#C7AE95
color2=#cc5279
color3=#6690da
color4=#000000
color5=#C795AE
color6=#4f97d7
color7=#C7CCD1
color8=#747C84
color9=#C7AE95
color10=#95C7AE
color11=#AEC795
color12=#bb6dc4
color13=#C795AE
color14=#95AEC7
color15=#F3F4F5
color16=#C7C795
color17=#C79595
color18=#393F45
color19=#565E65
color20=#ADB3BA
color21=#DFE2E5

**Comment by fornwall** [comment]
@AbdullahM0hamed Thanks a lot! This theme is now part of version 0.26 of the Termux:Styling app, which will be available as an update in a few hours.
