### ISSUE TITLE
Could we please add the Terminus font?

### ISSUE THREAD

**Issue by kriskropd** [termux/termux-styling#62]
I realize you can't include every font that users might request, but this really should be a font to consider if you're including monospaced fonts that are actually popular with shell users.

http://terminus-font.sourceforge.net/

**Comment by xeffyr** [comment]
I don't see any TTF file within its archives.
PCF & BDF fonts are not supported.

**Comment by kriskropd** [comment]
https://files.ax86.net/terminus-ttf/

**Comment by xeffyr** [comment]
@kriskropd Thanks, now I'm re-opening this.

**Comment by fornwall** [comment]
@kriskropd Thanks! This font will be available in version 0.26 of the Termux:Styling app, which will be available within a few hours.
