### ISSUE TITLE
What colors control what?

### ISSUE THREAD

**Issue by Vortetty** [termux/termux-styling#65]
what color properties in the colors.properties file control what?

for example, what color is color0 controlling?
the ones below are obvious but what colors do the non-descript colors control
foreground=#a5a2a2
background=#090300
cursor=#a5a2a2

**Comment by xeffyr** [comment]
> what color is color0 controlling

Black.

> what colors do the non-descript colors control

They control each of the available 256 terminal colors. See https://github.com/termux/termux-app/blob/master/terminal-emulator/src/main/java/com/termux/terminal/TerminalColorScheme.java for more information.

Also, chart with 256 colors - https://upload.wikimedia.org/wikipedia/commons/1/15/Xterm_256color_chart.svg.

**Comment by Vortetty** [comment]
thank you!

**Comment by Vortetty** [comment]
@xeffyr do you happen to know where i could find the default color scheme?
