### ISSUE TITLE
Error Installing Termux Styling

### ISSUE THREAD

**Issue by Jensenkho** [termux/termux-styling#76]
![Screenshot_20200305_220620_com offsec nethunter store](https://user-images.githubusercontent.com/47233603/75989155-b995f100-5f2d-11ea-8331-6a3aeed55c47.jpg)

**Problem description**
Download Nethunter store, try to install Termux Styling but error occurs.
**Additional information**

* Termux application version: 0.92
* Android OS version: 9
* Device model: Huawei P20

**Comment by xeffyr** [comment]
> Download Nethunter store

Is Termux app downloaded from Nethunter store too ? Make sure that it is, because add-on signature must be same as of Termux app.

**Comment by Jensenkho** [comment]
I uninstall Termux which I download from Play Store & reinstall Termux from Nethunter store, still encounter same error. 
Please do not close this issue because the error still occur. 

![Screenshot_20200306_050149_com offsec nethunter store](https://user-images.githubusercontent.com/47233603/76025682-6beaaa00-5f68-11ea-9592-027a8d5d9905.jpg)

**Comment by Grimler91** [comment]
@Jensenkho you need to install **all** termux apps from nethunter store, so uninstall termux-api, termux-boot and whatever other termux apps you have installed from google play 

If you can get a logcat from adb showing what the actual error is then we can consider re-opening it
