### ISSUE TITLE
Strange Permission requirements?

### ISSUE THREAD

**Issue by ouiji** [termux/termux-styling#9]
When attempting to install via F-Droid it requires permissions to:

Phone state/identity
Read/Send text messages
Take pictures/video
Record audio
Net/GPS location
Read contacts
Read/write SD card
Full net access
Draw over apps
Prevent sleep
Transmit infrared!?

These permissions don't quite seem quite right.. am I missing somthing?

**Comment by fornwall** [comment]
For the core Termux app, or for the add-ons? The core Termux app does not request many permissions, but the add-ons (especially the API one) do.
