### ISSUE TITLE
ERROR Installing Termux:Styling app using apk from F-Droid

### ISSUE THREAD

**Issue by Rehan-Phantom** [termux/termux-styling#94]
**Problem description**
Terux Stylign app won't install, it says error install app

**Steps to reproduce**
Download apk of app from F-Droid and install

**Expected behavior**
Expected app to install normally and no problems 

**Additional information**

* Termux application version: 0.95
* Android OS version: 8.1
* Device model: Samsung Galaxy Tab A 2016

**Comment by Grimler91** [comment]
You need to install all apps from the same source, i.e. all apps from google play or all apps from fdroid. Installation sources can't be mixed as the apps for fdroid have been signed with another key than the apps for google play.

See also the termux wiki on termux:styling: https://wiki.termux.com/wiki/Termux:Styling
